### ISSUE TITLE
Build and Push docker images to container registry

### ISSUE THREAD

**Issue by GoldJns** [GoldJns/rateme-nextgen#47]
**Is your feature request related to a problem? Please describe.**
Images should not be stored locally, better in a container registry

**Describe the solution you'd like**
Github Container Registry/Github Package is a good option, can be integrated in github actions workflow

**Comment by GoldJns** [comment]
Done... Images are pushed to Github Container registry. Deployment to registry will be triggered on push/merge to main(take a look at `build-push-images `). 

*Packages*
- rateme-nextgen-ui
- rateme-nextgen-backend
- rateme-nextgen-database

![image](https://github.com/GoldJns/rateme-nextgen/assets/88201439/c01d945d-199f-40b4-97f9-7aab07a5e82b)
![image](https://github.com/GoldJns/rateme-nextgen/assets/88201439/d87db94b-5ac1-4ec7-81a0-25689f4ee07d)

**Comment by GoldJns** [comment]
Examle: you could reference this image simply in the docker-compose file and it will work: services:
 ```yaml
 backend:
    image: ghcr.io/goldjns/rateme-nextgen-backend:v1.3.2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/rateme_swtp
      - SPRING_DATASOURCE_USERNAME=root
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8080:8080
```
